model_params:  
  descrip: |
            
            -Experiment 8
            -U-net kind of architecture with inception block for clear image, with transMap also for decoer part
            -No Deconv layer is used in this, upsampling is done and then conv is used.
            -Numbers of feature map are in order of 16, 32,64,32,16,3
            -Batch Norm is used in all just not in first and last
            -No loss other than adversarial loss and L1 loss is used and MSE for transMap
            -Discriminator is taken from pix2pix-affiine_layer with some changes in no. of feature_maps
            -All hyper parameters same as used in my_pix2pix, only the changes is made in gen and Discriminator
            -No weight regularization
            -Difference from Exp 6: Use of TransMap  

  model_name: "U-net-inception-noDecovn-TransMap" # DD or MSCNN or AOD or pix2pix or 
  mode: "train"   # train or test
  log_dir: /media/mnt/dehaze/dehazeGan_logs/ # path to write the model and load the model

training_params:
  learning_rate: 1e-04
  epochs: 201
  batch_size: 16
  # data_path: /media/mnt/dehaze/data/ChinaMM18dehaze/  # Path from where to load the data
  data_path: /media/mnt/dehaze/data/cityscape/processed/
