model_params:  
  descrip: |
            Generator have exact densenet architecture with 5 Conv layers.
            Output feature map of every conv layer have depth of 3.
            Batch Norm is used in conv 2,3,4
            No transMap inforamtion is used
            No loss other than adversarial loss and L1 loss is used.
            Discriminator is taken from pix2pix-affiine_layer with some changes in no. of feature_maps
            All hyper parameters same as used in my_pix2pix, only the changes is made in gen and Discriminator
            No weight regularization

  model_name: "" # DD or MSCNN or AOD or pix2pix or 
  mode: "test"   # train or test
  log_dir: /media/mnt/dehaze/dehazeGan_logs/ # path to write the model and load the model

training_params:
  learning_rate: 1e-04
  epochs: 201
  batch_size: 32
  # data_path: /media/mnt/dehaze/data/ChinaMM18dehaze/  # Path from where to load the data
  data_path: /media/mnt/dehaze/data/cityscape/processed/
